"""first LaitGooddb_20220520

Revision ID: 71fb3e35a733
Revises: 
Create Date: 2022-05-20 18:04:02.818170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71fb3e35a733'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LaitGood_Adminlogin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LaitGood_Adminlogin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('admin', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=50), nullable=False),
    sa.Column('role', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('role IN (0, 1)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin')
    )
    # ### end Alembic commands ###
