"""20220728SQLite更動

Revision ID: 89cde2861bf9
Revises: e37dbd048cd0
Create Date: 2022-07-28 13:05:23.973547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89cde2861bf9'
down_revision = 'e37dbd048cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LaitGood_Shoppingorder', sa.Column('t_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'LaitGood_Shoppingorder', 'LaitGood_Transaction', ['t_id'], ['t_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'LaitGood_Shoppingorder', type_='foreignkey')
    op.drop_column('LaitGood_Shoppingorder', 't_id')
    # ### end Alembic commands ###
