"""20220706更

Revision ID: e37dbd048cd0
Revises: 23605aeccd97
Create Date: 2022-07-06 17:45:22.782659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37dbd048cd0'
down_revision = '23605aeccd97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LaitGood_Shoppingdata', sa.Column('product_sellprice', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LaitGood_Shoppingdata', 'product_sellprice')
    # ### end Alembic commands ###
